// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using site_pessoal_dinamico.Data;

namespace site_pessoal_dinamico.Migrations
{
    [DbContext(typeof(SitePessoalBdContext))]
    partial class SitePessoalBdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("site_pessoal_dinamico.Models.distincao_premios", b =>
                {
                    b.Property<int>("distincao_premiosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao_distincao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("distincao_premiosId");

                    b.ToTable("distincao_premios");
                });

            modelBuilder.Entity("site_pessoal_dinamico.Models.experiencia_profissional", b =>
                {
                    b.Property<int>("experiencia_profissionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao_exp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("funcao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("experiencia_profissionalId");

                    b.ToTable("experiencia_profissional");
                });

            modelBuilder.Entity("site_pessoal_dinamico.Models.formacao", b =>
                {
                    b.Property<int>("formacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("competencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_curso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_instituicao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("formacaoId");

                    b.ToTable("formacao");
                });

            modelBuilder.Entity("site_pessoal_dinamico.Models.outras_informacoes", b =>
                {
                    b.Property<int>("outras_informacoesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao_informacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("outras_informacoesId");

                    b.ToTable("outras_informacoes");
                });

            modelBuilder.Entity("site_pessoal_dinamico.Models.skills", b =>
                {
                    b.Property<int>("skillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao_skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("skillsId");

                    b.ToTable("skills");
                });
#pragma warning restore 612, 618
        }
    }
}
